version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      DATABASE_URL: jdbc:mysql://localhost:3306/mydatabase?user=myuser&password=mypassword
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
