version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
